name: Test

on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:

  test:
    runs-on: windows-latest
    environment: Development
    steps:
    - name: Hello
      run: echo "Hola"
      shell: pwsh
